### ISSUE TITLE
Unparser

### ISSUE THREAD

**Issue by QuentinJanuel** [ClarotyICS/access_parser#2]
Hi, thank you very much for the amazing work!

Is there any plan for an unparse feature too?

**Comment by ur1katz** [comment]
Thanks @QuentinJanuel
Re-building the database requires parsing all of the column fields and is a bit more complex than just reversing the parsing process.
I don’t think we will be adding support for it any time soon but i’m more than happy to help with any pull request.

**Comment by QuentinJanuel** [comment]
Alright, thank you for the quick reply
I don't know if I will have time to implement the unparser myself anytime soon either because I still don't know anything about the files structures, but I first need to rewrite your code in JavaScript anyway so I will start with that

**Comment by ur1katz** [comment]
Here are some really good links for understanding the file structure :) 
http://jabakobob.net/mdb/ 
https://github.com/brianb/mdbtools/blob/master/HACKING
